admin_panel/urls.py
from django.urls import path
from . import views

app_name = 'admin_panel'

urlpatterns = [
    path('', views.admin_panel, name='admin_panel'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('categories/', views.category_list, name='category_list'),
    path('categories/create/', views.create_category, name='create_category'),
    path('category/update/<int:pk>/', views.update_category, name='update_category'),
    path('category/delete/<int:pk>/', views.delete_category, name='delete_category'),
    path('products/', views.product_list, name='product_list'),
    path('products/create/', views.create_product, name='create_product'),
    path('products/update/<int:pk>/', views.update_product, name='update_product'),
    path('products/delete/<int:pk>/', views.delete_product, name='delete_product'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('update/<int:item_id>/', views.update_cart_item, name='update_cart_item'),
    path('remove/<int:item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('detail/', views.cart_detail, name='cart_detail'),
    path('checkout/', views.checkout, name='checkout'),
]

category/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('category/<slug:slug>/', views.category_products, name='category_products'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from products import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),  # Включаем URL из приложения main
    path('category/', include('category.urls')),  # Убедитесь, что вы включили URL приложения category
    path('products/', include('products.urls')),  # Включаем URL приложения products, если такое имеется
    path('admin_panel/', include('admin_panel.urls', namespace = "admin_panel")), #с помощью namespace изолируем admin_panel
    path('get-category-attributes/', views.get_category_attributes, name='get_category_attributes'),
    path('cart/', include('cart.urls')),
]

# Настройка для обработки медиафайлов
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

category/models.py
from django.db import models
from django.utils.text import slugify

class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    def save(self, *args, **kwargs):
        if not self.slug:  # Проверяем, пуст ли slug
            self.slug = slugify(self.name)  # Генерируем slug из названия
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name
    




class Attribute(models.Model):
    name = models.CharField(max_length=50)
    category = models.ForeignKey(Category, related_name='attributes', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} (Category: {self.category.name})"

admin_panel/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):
    password1 = forms.CharField(
        label="Пароль",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        help_text="Введите надёжный пароль.",
    )
    password2 = forms.CharField(
        label="Подтверждение пароля",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        help_text="Введите тот же пароль для подтверждения.",
    )

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
        labels = {
            'username': 'Логин',
        }
        help_texts = {
            'username': None,  # Убираем стандартные подсказки для логина
        }

admin_panel/views.py
import re
from django.db import IntegrityError
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.views.generic import CreateView
from category.models import Category, Attribute
from products.models import Product, ProductAttributeValue
from django.utils.text import slugify
from django.core.paginator import Paginator
from django.contrib.auth import authenticate, login, logout,login as auth_login
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse,reverse_lazy
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm
from unidecode import unidecode




def superuser_required(view_func):
    def wrapper(request, *args, **kwargs):
        if not request.user.is_superuser:
            # Добавление сообщения об ошибке
            messages.error(request, "У вас нет доступа к этому модулю. Доступ только для администраторов.")
            return redirect('/')  # Перенаправление на главную страницу или другую публичную страницу
        return view_func(request, *args, **kwargs)
    return wrapper


@superuser_required
def admin_panel(request):
    return render(request,'admin_panel/admin_panel.html')

def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Регистрация прошла успешно! Вы можете войти в систему.')
            return redirect('admin_panel:login') 
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'admin_panel/register.html', context)


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request,username=username,password=password)

    

        if user is not None:
            auth_login(request, user)  # Используем alias auth_login
            return redirect('admin_panel:admin_panel')
        else:
            messages.error(request, "Неправильное имя пользователя или пароль.")

    return render(request, 'admin_panel/login.html')


def logout_view(request):
    logout(request)
    return redirect('main')

@superuser_required
def category_list(request):
    category = Category.objects.all()
    paginator = Paginator(category, 3)  # Показать 5 авторов на странице
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request,'category/category_list.html',{'page_obj':page_obj})


@superuser_required
def product_list(request):
    search_query = request.GET.get('search', '')  # Получение строки поиска из GET-параметров
    products = Product.objects.all()
    
    # Фильтрация по названию, если указан поисковый запрос
    if search_query:
        products = products.filter(name__icontains=search_query)

    # Пагинация
    paginator = Paginator(products, 3)  # Показывать 3 продукта на странице
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'product/product_list.html', {
        'page_obj': page_obj,
        'search_query': search_query,  # Передаем строку поиска в шаблон
    })


@superuser_required
def create_category(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        description = request.POST.get('description')
        slug = request.POST.get('slug')  # Получаем слаг из формы
        attributes = request.POST.getlist('attributes[]')  # Получаем список атрибутов из формы

        # Если слаг не был введён, автоматически создаём его на основе имени категории
        if not slug:
            slug = generate_slug(name)

        # Проверка на уникальность slug
        if Category.objects.filter(slug=slug).exists():
            error_message = "Категория с таким slug уже существует."
            return render(request, 'category/create_category.html', {'error_message': error_message, 'name': name, 'description': description, 'slug': slug})

        try:
            # Создаем категорию
            category = Category.objects.create(
                name=name,
                description=description,
                slug=slug,
            )

            # Создаем атрибуты для категории, если они указаны
            for attribute_name in attributes:
                if attribute_name.strip():  # Проверяем, что атрибут не пустой
                    Attribute.objects.create(
                        name=attribute_name.strip(),
                        category=category
                    )

            return redirect('admin_panel:category_list')
        except IntegrityError:
            error_message = "Ошибка при сохранении категории."
            return render(request, 'category/create_category.html', {'error_message': error_message, 'name': name, 'description': description, 'slug': slug})

    return render(request, 'category/create_category.html')


# Функция для генерации слага на основе имени
def generate_slug(name):
    slug = name.lower()
    slug = slug.strip()
    slug = re.sub(r'\s+', '-', slug)  # Заменить пробелы на дефисы
    slug = re.sub(r'[^\w\-]+', '', slug)  # Удалить все неалфавитные символы
    return slug


@superuser_required
def create_product(request):
    categories = Category.objects.all()
    category_id = request.GET.get('category') or request.POST.get('category')
    attributes = Attribute.objects.filter(category_id=category_id) if category_id else []

    if request.method == 'POST':
        # Получение данных из формы
        name = request.POST.get('name')
        description = request.POST.get('description')
        price = request.POST.get('price')
        image = request.FILES.get('image')
        image2 = request.FILES.get('image2')
        image3 = request.FILES.get('image3')
        image4 = request.FILES.get('image4')

        # Валидация данных
        if not category_id or not name or not description or not price:
            messages.error(request, "Заполните все обязательные поля.")
            return render(request, 'product/create_product.html', {
                'categories': categories,
                'attributes': attributes,
                'category_id': category_id,
            })

        # Создание продукта
        slug = slugify(unidecode(name))
        if Product.objects.filter(slug=slug).exists():
            slug = f"{slug}-{Product.objects.filter(slug__startswith=slug).count() + 1}"

        try:
            price = float(price)
        except ValueError:
            messages.error(request, "Цена должна быть числом.")
            return render(request, 'product/create_product.html', {
                'categories': categories,
                'attributes': attributes,
                'category_id': category_id,
            })

        product = Product.objects.create(
            category_id=category_id,
            name=name,
            description=description,
            price=price,
            slug=slug,
            image=image,
            image2=image2,
            image3=image3,
            image4=image4
        )

        # Сохранение атрибутов
        for attribute in attributes:
            value = request.POST.get(f'attribute_values-{attribute.id}-value')
            if value:
                ProductAttributeValue.objects.create(
                    product=product,
                    attribute=attribute,
                    value=value
                )

        messages.success(request, "Продукт успешно создан.")
        return redirect('admin_panel:product_list')

    return render(request, 'product/create_product.html', {
        'categories': categories,
        'attributes': attributes,
        'category_id': category_id,
    })

@superuser_required
def update_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    attributes = category.attributes.all()  # Получаем атрибуты категории

    if request.method == 'POST':
        # Обновление полей категории
        category.name = request.POST.get('name', category.name)
        category.description = request.POST.get('description', category.description)
        category.slug = request.POST.get('slug', category.slug)
        category.save()

        # Обновление значений атрибутов
        for attribute in attributes:
            new_value = request.POST.get(f'attribute_{attribute.id}')
            if new_value:
                attribute.name = new_value
                attribute.save()

        return redirect('admin_panel:category_list')

    return render(request, 'category/update_category.html', {'category': category, 'attributes': attributes})


@superuser_required
def update_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    category_attributes = product.category.attributes.all()  # Получаем атрибуты категории

    if request.method == 'POST':
        # Обновляем основные поля продукта
        product.name = request.POST.get('name', product.name)
        product.description = request.POST.get('description', product.description)
        product.slug = request.POST.get('slug', product.slug)
        product.price = request.POST.get('price', product.price)

        # Обновляем изображения, если они переданы
        if 'image' in request.FILES:
            product.image = request.FILES['image']
        if 'image2' in request.FILES:
            product.image2 = request.FILES['image2']
        if 'image3' in request.FILES:
            product.image3 = request.FILES['image3']
        if 'image4' in request.FILES:
            product.image4 = request.FILES['image4']

        product.save()  # Сохраняем изменения продукта

        # Сохранение значений атрибутов
        for attribute in category_attributes:
            value = request.POST.get(f'attribute_{attribute.id}')
            if value:

category/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category
from products.models import Product  # Замените your_app на название приложения, где находится модель Product

def category_products(request, slug):
    category = get_object_or_404(Category, slug=slug)
    products = Product.objects.filter(category=category)
    return render(request, 'category/category_products.html', {'category': category, 'products': products})

admin_panel/templates/category/category_list.html
{% extends 'admin.html' %}
{% block admin %}
<div class="box-author">
    <div class="create">
        <h1>Категории</h1>
        <button type="button" class="btn btn-success"><a href="{% url 'admin_panel:create_category' %}">Добавить Категорию</a></button>
    </div>
    
    <table class="table">
        <tr>
            <th>Название категории</th>
            <th>Описание</th>
            <th>Слаг</th>
            <th>Редактирование</th>
            <th>Удаление</th>
        </tr>
        {% for category in page_obj %}
        <tr>
            <td>{{ category.name }}</td>
            <td>{{ category.description|slice:":80" }}{% if category.description|length > 80 %}...{% endif %}</td>
            <td>{{ category.slug }}</td>
            <td><button type="button" class="btn btn-warning"><a href="{% url 'admin_panel:update_category' category.pk %}">Редактировать</a></button></td>
            <td><button type="button" class="btn btn-danger"><a href="{% url 'admin_panel:delete_category' category.pk %}">Удалить</a></button></td>
        </tr>
        {% endfor %}
    </table>
    
    <!-- Пагинация -->
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; Первая</a>
                <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
            {% endif %}
            
            <span>Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</span>
            
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
            {% endif %}
        </span>
    </div>
    
</div>
{% endblock %}

admin_panel/templates/category/create_category.html
{% extends 'admin.html' %}
{% block admin %}

<div class="box-book">
    
    <form method="post">
        {% csrf_token %}
        
        <label for="name">Название категории:</label>
        <input type="text" name="name" id="name" class="alert alert-info" oninput="generateSlug()"><br>
                
        <label for="description">Описание:</label>
        <input type="text" name="description" id="description" class="alert alert-info"><br>
        
        <label for="slug">Слаг:</label>
        <input type="text" name="slug" id="slug" class="alert alert-info"><br>
        
        <!-- Поля для добавления атрибутов -->
        <div id="attributes-container">
            <label>Атрибуты:</label>
            <div class="attribute-field">
                <input type="text" name="attributes[]" placeholder="Название атрибута" class="alert alert-info">
            </div>
        </div>
        
        <!-- Кнопка для добавления новых полей атрибутов -->
        <button type="button" onclick="addAttributeField()" class="btn btn-secondary">Добавить атрибут</button><br><br>
        
        <button type="submit" class="btn btn-success">Создать категорию</button>
        
    </form>
    
</div>

<div class="footer">
    <a href="{% url 'admin_panel:category_list' %}" class="btn btn-primary">Назад</a>
</div>

<script>
    // Функция для транслитерации русского текста в латиницу
    function transliterate(text) {
        const ruToEn = {
            а: 'a', б: 'b', в: 'v', г: 'g', д: 'd', е: 'e', ё: 'yo', ж: 'zh', з: 'z', и: 'i', 
            й: 'y', к: 'k', л: 'l', м: 'm', н: 'n', о: 'o', п: 'p', р: 'r', с: 's', т: 't', 
            у: 'u', ф: 'f', х: 'h', ц: 'ts', ч: 'ch', ш: 'sh', щ: 'shch', ы: 'y', э: 'e', 
            ю: 'yu', я: 'ya', 
            // Верхний регистр
            А: 'A', Б: 'B', В: 'V', Г: 'G', Д: 'D', Е: 'E', Ё: 'YO', Ж: 'ZH', З: 'Z', И: 'I', 
            Й: 'Y', К: 'K', Л: 'L', М: 'M', Н: 'N', О: 'O', П: 'P', Р: 'R', С: 'S', Т: 'T', 
            У: 'U', Ф: 'F', Х: 'H', Ц: 'TS', Ч: 'CH', Ш: 'SH', Щ: 'SHCH', Ы: 'Y', Э: 'E', 
            Ю: 'YU', Я: 'YA'
        };
        return text.split('').map(char => ruToEn[char] || char).join('');
    }

    // Функция для генерации слага на основе имени категории
    function generateSlug() {
        var name = document.getElementById('name').value;
        var slugField = document.getElementById('slug');

        // Преобразуем имя в нижний регистр, заменяем пробелы на дефисы
        var slug = name.toLowerCase().trim();
        slug = transliterate(slug); // Применяем транслитерацию
        slug = slug.replace(/\s+/g, '-'); // Заменяем пробелы на дефисы
        slug = slug.replace(/[^a-z0-9\-]+/g, ''); // Убираем все неалфавитные символы, оставляем только латиницу, цифры и дефисы
        slugField.value = slug;
    }

    // Скрипт для добавления новых полей атрибутов
    function addAttributeField() {
        const container = document.getElementById('attributes-container');
        const newField = document.createElement('div');
        newField.classList.add('attribute-field');
        newField.innerHTML = '<input type="text" name="attributes[]" placeholder="Название атрибута" class="alert alert-info">';
        container.appendChild(newField);
    }
</script>



{% endblock %}

admin_panel/templates/category/delete_category.html
{% extends 'admin.html' %}

{% block admin %}

<div class="box-delete">
  <h1>Удалить категорию</h1>
<p>Вы уверены, что хотите удалить категорию "{{ category.name }}"?</p>
<form method="post">
  {% csrf_token %}
  <button class="btn btn-danger" type="submit">Удалить</button>  <a class="btn btn-primary" href="{% url 'admin_panel:category_list' %}">Назад</a>
</form>

</div>


{% endblock%}

admin_panel/templates/category/update_category.html
{% extends 'admin.html' %}
{% block admin %}
<div class="container mt-4">
    <h2 class="mb-4">Редактирование категории</h2>
    <form method="post" enctype="multipart/form-data" class="form-group">
        {% csrf_token %}
        
        <div class="form-group row">
            <label for="name" class="col-sm-2 col-form-label">Название:</label>
            <div class="col-sm-10">
                <input class="form-control custom-input" type="text" name="name" id="name" value="{{ category.name }}" required>
            </div>
        </div>

        <div class="form-group row">
            <label for="description" class="col-sm-2 col-form-label">Описание:</label>
            <div class="col-sm-10">
                <textarea class="form-control custom-input" name="description" id="description" rows="8" required>{{ category.description }}</textarea>
            </div>
        </div>
        

        <div class="form-group row">
            <label for="slug" class="col-sm-2 col-form-label">Слаг:</label>
            <div class="col-sm-10">
                <input class="form-control custom-input" type="text" name="slug" id="slug" value="{{ category.slug }}" required>
            </div>
        </div>

        <h3 class="mt-4">Атрибуты категории:</h3>
        {% if attributes %}
            <ul class="list-unstyled">
                {% for attribute in attributes %}
                    <li class="mb-3">
                        <label for="attribute_{{ attribute.id }}" class="font-weight-bold">{{ attribute.name }}:</label>
                        <input class="form-control custom-input" type="text" name="attribute_{{ attribute.id }}" id="attribute_{{ attribute.id }}" value="{{ attribute.name }}">
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Нет атрибутов для этой категории.</p>
        {% endif %}

        <button class="btn btn-success" type="submit">Сохранить</button>
    </form>
</div>

{% block extra_css %}
<style>
    /* Центрирование и установка полупрозрачности */
    .custom-input {
        width: 100%; /* Ширина поля на 100% от контейнера */
       
        border: 1px solid rgba(0, 0, 0, 0.2); /* Легкая обводка для контраста */
        padding: 10px; /* Отступы внутри поля */
    }

    /* Стили для формы */
    .form-group label {
        font-weight: bold; /* Сделаем текст метки жирным */
    }

    /* Поля ввода должны быть на одном уровне с метками */
    .form-group {
        margin-bottom: 15px;
    }

    /* Дополнительные стили для кнопки */
    .btn {
        margin-top: 20px;
    }
</style>
{% endblock %}
{% endblock %}