admin_panel/urls.py
from django.urls import path
from . import views

app_name = 'admin_panel'

urlpatterns = [
    path('', views.admin_panel, name='admin_panel'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('categories/', views.category_list, name='category_list'),
    path('categories/create/', views.create_category, name='create_category'),
    path('category/update/<int:pk>/', views.update_category, name='update_category'),
    path('category/delete/<int:pk>/', views.delete_category, name='delete_category'),
    path('products/', views.product_list, name='product_list'),
    path('products/create/', views.create_product, name='create_product'),
    path('products/update/<int:pk>/', views.update_product, name='update_product'),
    path('products/delete/<int:pk>/', views.delete_product, name='delete_product'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('update/<int:item_id>/', views.update_cart_item, name='update_cart_item'),
    path('remove/<int:item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('detail/', views.cart_detail, name='cart_detail'),
    path('checkout/', views.checkout, name='checkout'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from products import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),  # Включаем URL из приложения main
    path('category/', include('category.urls')),  # Убедитесь, что вы включили URL приложения category
    path('products/', include('products.urls')),  # Включаем URL приложения products, если такое имеется
    path('admin_panel/', include('admin_panel.urls', namespace = "admin_panel")), #с помощью namespace изолируем admin_panel
    path('get-category-attributes/', views.get_category_attributes, name='get_category_attributes'),
    path('cart/', include('cart.urls')),
]

# Настройка для обработки медиафайлов
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.utils.text import slugify
from category.models import Category, Attribute  # Импортируем модель Category и Attribute


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=0)
    image = models.ImageField(upload_to='products/images/', blank=True, null=True)
    image2 = models.ImageField(upload_to='products/images/', blank=True, null=True)
    image3 = models.ImageField(upload_to='products/images/', blank=True, null=True)
    image4 = models.ImageField(upload_to='products/images/', blank=True, null=True)
    slug = models.SlugField(max_length=255, blank=True, unique=True)  # Поле для slug

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:  # Если slug не заполнен
            category_slug = slugify(self.category.name)  # Слаг для категории
            product_slug = slugify(self.name)  # Слаг для продукта
            self.slug = f"{category_slug}-{product_slug}"  # Формируем общий слаг для продукта

            # Проверка уникальности слага
            if Product.objects.filter(slug=self.slug).exists():
                self.slug = f"{self.slug}-{Product.objects.filter(slug__startswith=self.slug).count() + 1}"

        super().save(*args, **kwargs)



class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_images')
    image = models.ImageField(upload_to='products/images/')
    is_main = models.BooleanField(default=False)

    def __str__(self):
        return f"Изображение для {self.product.name}"


class ProductAttributeValue(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='attribute_values')
    attribute = models.ForeignKey(Attribute, on_delete=models.CASCADE)
    value = models.CharField(max_length=255)  # Значение атрибута для продукта (например, "Красный", "L")

    def __str__(self):
        return f"{self.product.name} - {self.attribute.name}: {self.value}"

templates/admin.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin панель</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
    <div class="containerr">
        <div class="header">
            <div>
                <button class="btn btn-info btn-lg"> <a href="{% url 'main' %}">Главная страница</a></button>
            </div>

            <div>
                <!-- <form method="POST" action=" url 'users:logout' "> -->
                {% csrf_token %}
                <!-- <button type="submit" class="btn btn-dark btn-lg">Выйти</button> -->
                <!-- </form> -->
            </div>

        </div>
        <div class="content">

            <div class="nav">
                <ul>
                    <li><a href="{% url 'admin_panel:category_list' %}">Категории</a></li>
                    <li><a href="{% url 'admin_panel:product_list' %}">Продукты</a></li>
                </ul>


            </div>
            <div class="info">
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}

                {% block admin %}

                {% endblock %}
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ecommerse</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>

<body>
    <header class="bg-light p-3">
        <a href="{% url 'main' %}" class="logo">
            MD-Store
        </a>
        <div class="catalog dropdown">
            <!-- Кнопка для открытия списка -->
            <a href="#" class="btn btn-light dropdown-toggle" id="catalogDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                Каталог
            </a>
            <!-- Выпадающее меню -->
            <ul class="dropdown-menu" aria-labelledby="catalogDropdown">
                {% for category in categories %}
                    {% if category.slug %}
                        <li><a class="dropdown-item" href="{% url 'products_by_category' category.slug %}">{{ category.name }}</a></li>
                    {% else %}
                        <li><span class="dropdown-item">{{ category.name }}</span></li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
        
        <!-- поиск по имени и описанию продукта категории -->
        {% block search %}
        <form action="{% url 'search_results' %}" method="get" class="d-flex">
            <input type="text" name="q" class="form-control" placeholder="Поиск по имени продукта" value="{{ request.GET.q }}">
            <button type="submit" class="btn btn-primary">Поиск</button>
        </form>
        
        {% endblock %}
        
        <div class="links">
            <ul class="list-inline mb-0">
                <li class="list-inline-item">
                    <a href="{% url 'cart:view_cart' %}">
                        {% if cart_item_count > 0 %}
                            <span class="badge bg-warning ms-2"><i class="fas fa-cart-plus"></i> {{ cart_item_count }}</span>  <!-- ms-2 для отступа -->
                        {% endif %}
                    </a>
                </li>
                {% if not user.is_authenticated %}
                    <li><a class="btn btn-warning" href="{% url 'admin_panel:register' %}">Регистрация</a></li>
                    <li><a class="btn btn-primary" href="{% url 'admin_panel:login' %}">Войти</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                    <form action="{% url 'admin_panel:logout' %}" method="POST" style="display:inline;">
                        {% csrf_token %}
                        <button class="btn btn-danger" type="submit">Выйти</button>
                    </form>
                    <li>
                        {% if user.is_superuser %}
                            <a class="btn btn-primary" href="{% url 'admin_panel:admin_panel' %}">Админ</a>
                        {% endif %}
                    </li>
                    
                {% endif %}
            </ul>
        </div>
    </header>
    <div class="box">
        <div class="info-blog">
            <div class="nav-blog">
                <form method="get" class="mb-4 text-center">
                    <div class="d-flex flex-column align-items-center gap-3">
                        <!-- Поле для поиска по имени -->
                        <div style="width: 300px;">
                            <input 
                                type="text" 
                                name="q" 
                                placeholder="Поиск по имени" 
                                value="{{ search_query }}" 
                                class="form-control"
                            />
                        </div>
                
                        <!-- Поля для фильтрации по цене -->
                        <div style="width: 300px;">
                            <input 
                                type="number" 
                                name="min_price" 
                                placeholder="Мин. цена" 
                                value="{{ min_price }}" 
                                class="form-control"
                            />
                        </div>
                        <div style="width: 300px;">
                            <input 
                                type="number" 
                                name="max_price" 
                                placeholder="Макс. цена" 
                                value="{{ max_price }}" 
                                class="form-control"
                            />
                        </div>
                
                        <!-- Фильтрация по атрибутам -->
                        {% for attribute in category_attributes %}
                            <div style="width: 300px;">
                                <select name="attributes" class="form-select">
                                    <option value="">{{ attribute.name }}</option>
                                    {% for value in attribute.productattributevalue_set.all %}
                                        <option 
                                            value="{{ value.value }}" 
                                            {% if value.value in selected_attributes %}selected{% endif %}
                                        >
                                            {{ value.value }}
                                        </option>
                                    {% endfor %}
                                </select>
                            </div>
                        {% endfor %}
                
                        <!-- Кнопка для выполнения поиска -->
                        <div style="width: 300px;">
                            <button type="submit" class="btn btn-primary w-100">Поиск</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="content-blog">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

</body>

</html>